import type {Metadata} from "next";
import {Modak} from "next/font/google";
import "./globals.css";

const font = Modak({
    weight: "400",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Zappis TO-DO",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={font.className}>{children}</body>
        </html>
    );
}
