import type {Metadata} from "next";
import {Modak, Rubik_Mono_One, Space_Grotesk} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner"

const font3 = Rubik_Mono_One({
    weight: "400",
    subsets: ["latin"]
})

const font2 = Space_Grotesk({
    weight: "400",
    subsets: ["latin"]
})

const font = Modak({
    weight: "400",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Zappis TO-DO",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body className={font3.className}>{children}
        <Toaster/>
        </body>

        </html>
    );
}
